#!/usr/bin/env bash
# redirect 
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
