#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server.
apt-get -y update
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-3.0 -y
apt-get -y update
apt-get install haproxy=3.0.\*

echo '
frontend developmentdesign.tech
        bind *:80
        mode http
        timeout client 60s
        default_backend web_servers

backend web_servers
        balance roundrobin
        timeout connect 10s
        timeout server 100s
        mode http
        server 659303-web-01 100.26.253.64:80 check
        server 659303-web-02 54.152.64.223:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
