#!/bin/env bash
#This script is displaying "Best School" 10 times and say "Hi" in the 9th
c=0
while [ $c -lt 10 ]
do
    echo "Best School"
    if [ $c == 8 ]
    then
        echo "Hi"
    fi
    ((c++))
done
